baseURL = "https://misell.cymru"
title = "Benjamin Misell"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = "UA-112387098-1"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

pygmentsCodeFences = true

pygmentsOptions = ""
pygmentsUseClasses = false
pygmentsUseClassic = false

# See https://help.farbox.com/pygments.html
pygmentsStyle = "monokai"

# Missing translations will default to this content language
defaultContentLanguage = "en"

[outputs]
home = ["HTML", "AMP", "RSS"]
page = ["HTML"]

[params.info]
description = "A blog about random programing things"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = []
customJS = []
gopher = "https://storage.googleapis.com/gopherizeme.appspot.com/gophers/abc224b54c60ec9c4d84482e6fa2dcc25bbc17f4.png" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Benjamin Misell"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "Jan 02 2006"
listDateFormat = "Jan 02 2006"
hideEntryNavigation = ["page"] # boolean / array of sections
recentPostsLength = 4
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
homepageSections = ["recent_posts"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "legopicode" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = ""
email = "benjamin@misell.cymru"
facebook = ""
github = "BenjaminMisell"
instagram = ""
linkedin = ""
twitter = "legopicode"
telegram = ""

[params.social.config]
platforms = ["github","twitter","email"]

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "My company"
weight = -110
identifier = "company"
url = "https://fluidmedia.wales"

[[menu.main]]
name = "Tags"
weight = -120
identifier = "tags"
url = "/tags"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
