apiVersion: v1
kind: Namespace
metadata:
  name: misell-cymru
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
  namespace: misell-cymru
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: server
        kube-monkey/enabled: enabled
        kube-monkey/identifier: misell-cymru
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: 1
    spec:
      containers:
      - name: nginx
        image: evilben/misell_cymru
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: misell-cymru
  name: server
  labels:
    app: sever
spec:
  selector:
    app: server
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server
  namespace: misell-cymru
  labels:
    app: server
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - "misell.cymru"
    - "www.misell.cymru"
    secretName: server-tls
  rules:
  - host: "misell.cymru"
    http:
      paths:
      - path: "/"
        backend:
          serviceName: server
          servicePort: 80
  - host: "*.misell.cymru"
    http:
      paths:
      - path: "/"
        backend:
          serviceName: server
          servicePort: 80
